version: '3.5'
services:
  node:
    image: node:20
    hostname: node-20
    user: '1000:1000'
    environment:
      - TZ=Japan
      - color_prompt=yes
    working_dir: /home/node/vue-forms
    command: tail -f /dev/null
    volumes:
      - ./:/home/node/vue-forms